name: Matric Config

on: push

jobs:
    deploy:
      strategy:
        matrix:
          image: ["nginx:alpine3.22", "httpd:alpine3.23"]

      runs-on: self-hosted
      steps:
        - name: Echo Docker Details
          run: docker info

        - name: Run Image
          run: docker run --rm -d ${{matrix.image}}
