name: Matric Config

on: push

jobs:
    run-nginx:
        runs-on: self-hosted
        steps:
            - name: Echo Docker Details
              run: docker info

            - name: Run Image
              run: docker run --rm -p 81:80 nginx:alpine3.22

    run-httpd:
        runs-on: self-hosted
        steps:
            - name: Echo Docker Details
              run: docker info

            - name: Run Image
              run: docker run --rm -p 82:80 httpd:alpine3.23
